### ISSUE TITLE
OOM in CursorWindow create 

### ISSUE THREAD

**Issue by molikto** [requery/sqlite-android#11]
Hi,

I tried this project and I have got a lot of unexpected OOM crashes. The memory usage is not that high, but the CursorWindow allocation just fails (when `new CursorWindow()`). After switched to Android standard wrapper, OOM is gone. The only change is changing the imports from `io.requery.android.database` to `android.database` and also calling one method using reflection because it is not available in stock wrapper

````
	public static final void callBeginDeffered(SQLiteDatabase db) {
		Reflect.on(db).call("getThreadSession").call("beginTransaction", 0, (SQLiteTransactionListener) null, 1,null);
	}
```

This is probabality also happens in SQLite Android Binding, because I experienced some OOM this when I use the binding before. I switched to your version because there is x86 so files also you claim performance is different.


My code has a lot of concurrent queries, but the cursor is always closed after the data is read. Any thoughts why this happens?

**Comment by npurushe** [comment]
When do you close your Cursors or are you relying on the finalizer to close them?

**Comment by molikto** [comment]
I always read the data then explicitly close the cursor asap. This is possibly a problem in SQLite Android Binding. But I have no time to get a minimal test case now....

**Comment by npurushe** [comment]
Please try the 3.12.1-1 version

**Comment by molikto** [comment]
@npurushe OOM is gone

**Comment by npurushe** [comment]
Great! thanks for reporting

**Comment by molikto** [comment]
Hello. I can still reproduce this in certain phones...Galaxy Note3, Android 5.0

**Comment by npurushe** [comment]
Do you get any warnings in your adb log from the `SQLite` tag (or anything with the message `A resource was acquired at attached stack trace but never released`) ? Is it only on Android 5.0?

**Comment by molikto** [comment]
@npurushe no, there is none. but the native dirty memory will increase to around 60 mb. I can only reproduce it in one Android 5.0 phone, a Galaxy Note 3, with a Samsung custom Android 5.0. This is very wired to me, as the whole sqlite subsystem is in this project and shouldn't be platform dependent. Or it is not a real memory leak, but maybe it is because on that phone the memory constraint is different and this project doesn't meet the constraint but the system one meet.

**Comment by molikto** [comment]
@npurushe just read your README.md about the read performance. So this project allocate memory differently compared to "SQLite Android Binding" project and Android embedded SQLite?

**Comment by npurushe** [comment]
Yes that is the primary difference. I looked at the CursorWindow allocations and everything that was allocated was freed in all tests, so are you sure there is an issue there? How many cursors do you have open while running your program?
