### ISSUE TITLE
UnsatisfiedLinkError, couldn't find “libsqlite3x.so” when using io.requery:sqlite-android:3.28.0

### ISSUE THREAD

**Issue by IlyaGazman** [requery/sqlite-android#111]
Please see my question on StackOverflow:

https://stackoverflow.com/questions/56707144/unsatisfiedlinkerror-couldnt-find-libsqlite3x-so-when-using-io-requerysqlit

**Comment by M66B** [comment]
Did you maybe add

```
android {
  packagingOptions {
    exclude 'lib/...
```

to your build.gradle file? 

Maybe it will help to add

```android {
  defaultConfig {
   ndk {
    abiFilters "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
```

**Comment by M66B** [comment]
Maybe this is related to #105

**Comment by npurushe** [comment]
Yes this is a known bug on certain Android versions Relinker does solve it. You can call Relinker before invoking any of the sqlite-android apis and any System.loadLibrary call in sqlite-android would not fail. The .so file name could be exposed as a constant to make this simpler.
