### ISSUE TITLE
DriverManager

### ISSUE THREAD

**Issue by TheWhiteLlama** [requery/sqlite-android#112]
Hi!

I've just seen this repo and really loved the fact to be able to switch to the latest version. 
Currently my setup in my project has been done with sqldroid and the driver setup via the sql DriverManager. (like the old fashion jdbc handling)

```
DriverManager.registerDriver((Driver) Class.forName("org.sqldroid.SQLDroidDriver").newInstance());
DriverManager.getConnection("jdbc:sqldroid:database.db");
```

Is this also possible with requery sqlite?

Thanks!

**Comment by npurushe** [comment]
This project is specifically for android so it doesn't provide any jdbc integration. However in requery there is mapping on to a lot of the jdbc apis for the android api https://github.com/requery/requery/tree/master/requery-android/src/main/java/io/requery/android/sqlite although its not integrated as a driver.

Hope that helps!
