### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by vlivanov** [requery/sqlite-android#13]
It would be awesome to encrypt the entire database like sqlcipher does. 
https://github.com/sqlcipher/android-database-sqlcipher

**Comment by npurushe** [comment]
Using which extension? The official extension SEE has a paid license, this library supports loadable extensions so you can use it with that but you have to provide the binary, it can't be distributed with this library. SQLCipher maintains their own sqlite fork and copy of the android API already, so I don't think there is a need to duplicate that here.

**Comment by ohenepee** [comment]
With that said @npurushe It means there is not to attain full database encryption with this lib?
