### ISSUE TITLE
Gradle Failed to resolve 'io.query...'

### ISSUE THREAD

**Issue by pathnirvana** [requery/sqlite-android#132]
Added the following to gradle as instructed in Readme 
`implementation 'io.requery:sqlite-android:3.32.2'`

But then the gradle sync fails with the following error
`Failed to resolve: io.requery:sqlite-android:3.32.2`

A clean build is failing with this error
`Could not find io.requery:sqlite-android:3.32.2.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/io/requery/sqlite-android/3.32.2/sqlite-android-3.32.2.pom
  - https://jcenter.bintray.com/io/requery/sqlite-android/3.32.2/sqlite-android-3.32.2.pom
Required by:
    project :app`

Do I need to do anything else in Android studio in addition to the above line?
Sorry I am new to android native libraries

**Comment by pathnirvana** [comment]
I was able to solve the issue by downgrading to 
`implementation 'io.requery:sqlite-android:3.31.0'`
after noticing that https://mvnrepository.com/artifact/io.requery/sqlite-android?repo=jcenter has only 3.31.0

**Comment by pathnirvana** [comment]
I also had to add 
`implementation 'androidx.sqlite:sqlite:2.1.0'`
as a dependancy

Now when I built and deploy the app on an Android 10 device, I get the following error
`JNI FatalError called: Native registration unable to find class 'io/requery/android/database/sqlite/SQLiteConnection'; aborting...`
and the app crashes immediately

**Comment by mikehardy** [comment]
I don't believe @npurushe has published the latest commits as public versions yet, I don't see them as available either.

Here's a functional integration https://github.com/ankidroid/Anki-Android/blob/dc66eafac0885f3477127fe5c77eeac515ba6037/AnkiDroid/build.gradle#L221-L224

**Comment by pathnirvana** [comment]
Thank your @mikehardy for the reply. I tried this and unfortunately I am still getting the error.

Originally I was looking at this because I wanted to use FTS5, but then I migrated my code to use FTS4 and now working without requery-sqlite. It would have been nice if I was able to get this working though

**Comment by npurushe** [comment]
The latest version is published at this time, there was an issue where it was just staged in bintray and not published
