### ISSUE TITLE
minsdk 15

### ISSUE THREAD

**Issue by aegis123** [requery/sqlite-android#14]
Hi is there a specific reason why this library has minsdk 15 and not minsdk 14 or even minsdk 7?

**Comment by npurushe** [comment]
For 15 vs 14 see the answer [here](https://github.com/requery/requery/issues/105). For going even lower, that is possible but many of the SQLite exception classes and things like DatabaseUtils.getSqlStatementType weren't added until Honeycomb so this will have to be duplicated or thrown as generic.

**Comment by npurushe** [comment]
The 3.12.2-2 version supports API level 9 Gingerbread.
