### ISSUE TITLE
RequerySQLiteOpenHelperFactory is preventing Android Studio App Inspector from accessing database

### ISSUE THREAD

**Issue by lmj0011** [requery/sqlite-android#147]
I have requery added to my Room DB instance like so:

```kotlin
val db = Room.databaseBuilder(
   context.applicationContext,
   CourierLockerDatabase::class.java,
   "courier_locker_database"
 )
.openHelperFactory(RequerySQLiteOpenHelperFactory())
.build()
```

When I go to inspect the database in android studio via App Inspection, the database is closed..

![Screenshot from 2021-05-04 00-36-44](https://user-images.githubusercontent.com/9396189/116964383-02038880-ac71-11eb-9d00-15c7359e5b01.png)

If I remove the RequerySQLiteOpenHelperFactory, and rebuild app:
```kotlin
val db = Room.databaseBuilder(
   context.applicationContext,
   CourierLockerDatabase::class.java,
   "courier_locker_database"
 )
//.openHelperFactory(RequerySQLiteOpenHelperFactory())
.build()
```

The database is accessible like normal again. 
My guess is that requery is opening/closing the database instead of just keeping it open during the app's runtime....

If so, is there a way to change this behavior?

I'm using: `'com.github.requery:sqlite-android:3.35.4'`

**Comment by falcon4ever** [comment]
https://developer.android.com/studio/inspect/database

> Note: The Database Inspector only works with the SQLite library included in the Android operating system on API level 26 and higher. **It doesn't work with other SQLite libraries that you bundle with your app.**

I do wonder why though, in offline mode (after detaching the app and downloading the db) the Database Inspector is able to inspect the db and allows JSON1 commands as well

**Comment by lmj0011** [comment]
@falcon4ever 

> I do wonder why though, in offline mode (after detaching the app and downloading the db) the Database Inspector is able to inspect the db and allows JSON1 commands as well

May be that Android Studio loads the [json1 extension](https://www.sqlite.org/json1.html) in its version of sqlite.

Anyway it doesn't appear to be anything the devs can do about this, so I'll close this.
