### ISSUE TITLE
Incorrect POM published to jcenter

### ISSUE THREAD

**Issue by hvisser** [requery/sqlite-android#15]
In `build.gradle` a dependency on the support lib is specified, and it's resource ids packaged as `R.txt` into the published AAR. The `pom.xml` that is published does not declare any dependencies though. 

I'm trying to depend on your library in another library project and I get build errors regarding `R.txt`. I'm not sure if that is caused by the missing dependency, but I think it should be fixed anyway.

**Comment by npurushe** [comment]
Sure agree the dependency is missing from the pom, will update later today. Thanks for reporting.

**Comment by hvisser** [comment]
Thanks!

**Comment by npurushe** [comment]
The 3.12.2-2 version should be ok
