### ISSUE TITLE
License URL typo in build script

### ISSUE THREAD

**Issue by lfielke** [requery/sqlite-android#150]
The `build.gradle` [file](https://github.com/requery/sqlite-android/blob/9626fa37f62778297e6add045105e0b669a054f4/sqlite-android/build.gradle#L75) contains a typo in the URL for the Apache license. The current URL shows a 404 error instead of the expected license text.

This also impacts using automated license tools (such as https://github.com/cashapp/licensee), because they use exact matches for the URLs to determine which license a project is published under.

File has:  
http://www.apache.org/license/LICENSE-2.0.txt

Expected URL:  
http://www.apache.org/licenses/LICENSE-2.0.txt

Note the singular vs plural "license".

**Comment by npurushe** [comment]
thanks for reporting! will be updated in the next build
