### ISSUE TITLE
How can I integrate SqlCipher while using `RequerySQLiteOpenHelperFactory` with Room

### ISSUE THREAD

**Issue by iamriajul** [requery/sqlite-android#153]
Previously I had [android-database-sqlcipher](https://github.com/sqlcipher/android-database-sqlcipher) installed with Room using `SupportFactory` provided by the `SQLCipher` library, now I can't integrate this library with my Room using `RequerySQLiteOpenHelperFactory`, as I've seen in the Room's code that only one `OpenHelperFactory` can be used at a time.

So can you please suggest how can I solve my situation?

Thanks.

**Comment by iamriajul** [comment]
The discussions here has cleared my doubts: https://github.com/requery/sqlite-android/issues/13

**Comment by az-oolloow** [comment]
@iamriajul so what did you end up doing? not using `requery/sqlite-android`?
