### ISSUE TITLE
Version 3.37.2 not available

### ISSUE THREAD

**Issue by unveloper** [requery/sqlite-android#155]
Hi @npurushe 
I see that on the README the version indicated is 3.37.2, but on Jitpack the latest published is still the 3.36.0

Is there a problem? Can you please publish the latest version?

Thanks so much for you work

**Comment by npurushe** [comment]
Added a tag for that version which was missing I think that should resolve your issue

**Comment by unveloper** [comment]
Thanks but I thinks there was an error in the publish
https://jitpack.io/#requery/sqlite-android

https://jitpack.io/com/github/requery/sqlite-android/3.38.4/build.log

**Comment by JorgeCastilloPrz** [comment]
I understand [this](https://github.com/requery/sqlite-android/pull/157#issuecomment-1152136414) didn't fix the issue @npurushe?

**Comment by npurushe** [comment]
Latest version 3.39.2 is available, if a specific prior version is required that can be probably be added but will mark resolved for now.
