### ISSUE TITLE
Version 3.37.2 and 3.38.4 unavailable on Jitpack

### ISSUE THREAD

**Issue by benjdero** [requery/sqlite-android#158]
The last 2 versions are not available on Jitpack because the build failed: https://jitpack.io/com/github/requery/sqlite-android/3.38.4/build.log

**Comment by Kikadper** [comment]
Last usable version is 3.36.0

**Comment by JorgeCastilloPrz** [comment]
Wondering if there's a ETA for solving this. 3.36.0 was deployed in June 2021.

**Comment by npurushe** [comment]
Latest version 3.39.2 is available, if a specific prior version is required that can be probably be added but will mark resolved for now.
