### ISSUE TITLE
ProProguard rules

### ISSUE THREAD

**Issue by hvisser** [requery/sqlite-android#16]
The bundled ProGuard rules basically keep the entire library, both from shrinking and obfuscation. This is probably too broad, unless there's heavy use of reflection in the lib, so I'd like to request to either remove the generic ProGuard rules or to have more sensible defaults so that apps using this library can still strip and obfuscate parts of the library that they don't use.

**Comment by npurushe** [comment]
This is done more for the JNI interaction, e.g. native methods can't be removed or the method registration will fail & Java fields/classes are accessed which won't know about any obfuscation. Not sure proguard can really remove much but will provide an updated rules file.
