### ISSUE TITLE
x86_64 support?

### ISSUE THREAD

**Issue by guidedways** [requery/sqlite-android#17]
I wonder if 64-bit builds will be supported as these are soon becoming mainstream.

**Comment by npurushe** [comment]
Is this for the emulator or specific devices you're targeting? This wasn't included originally since this abi is mostly only common on desktop/emulators. Only concern is about library size, consumers of the library may need to filter out depending on what their app is for.

**Comment by bottiger** [comment]
@npurushe I understand your concern about library size, but I also want to vote for this. I don't know if there is a way of filtering out the x64 as default, but if not you could perhaps just publish a "debug/x64" version of the library which one can add as a gradle dependency.

**Comment by slightfoot** [comment]
I think the library should contain the precompiled .so files and then instructions to do split apks for ABI.

**Comment by npurushe** [comment]
This will be in the next release, the readme indicates how to exclude different abis if needed

**Comment by bottiger** [comment]
@npurushe Thank you very much
