### ISSUE TITLE
Custom functions support for Java bindings

### ISSUE THREAD

**Issue by livotov** [requery/sqlite-android#18]
Hi !

Any plans to add support for custom functions ?

**Comment by npurushe** [comment]
The original Android code contained this ability but it was hidden, however using this library you can use it like:

```java
SQLiteDatabase.CustomFunction functionCallback = new SQLiteDatabase.CustomFunction() {
            @Override
            public void callback(String[] args) {
                // do something with args
            }
        };
        SQLiteDatabaseConfiguration configuration =
            new SQLiteDatabaseConfiguration(mDatabaseFile.getPath(), SQLiteDatabase.CREATE_IF_NECESSARY);
        configuration.customFunctions.add(
            new SQLiteCustomFunction("CUSTOM_FUNCTION", numArgs, functionCallback));
        
```
However the custom function cannot return a value in the current implementation. Does that fit your use case?

**Comment by livotov** [comment]
yep, the idea was to return values too.
if you're not planning to add return values in the meantime, would you accept the pull request if we'll add such support ?

**Comment by npurushe** [comment]
Sure if you have PR that would be fine otherwise I can look into it as an enhancement. Looking at the documentation https://www.sqlite.org/c3ref/result_blob.html any implementation needs to be flexible enough to be able to return null/string/double/int/byte[]

**Comment by livotov** [comment]
Thanks. Just asked in order to decide whether should we fork it into a private branch or work on temp fork for PR for your master repo. Will let you know then once it implemented.

**Comment by livotov** [comment]
Hi ! Just to let you know we're testing our custom function with result value implementation, so hope to submit a PR back to you within several days. Cheers, Dmitri

**Comment by npurushe** [comment]
Great! thanks for the update

**Comment by vfaSonnt** [comment]
How is it going? I really hope this feature release. Thanks for your work.

**Comment by npurushe** [comment]
This will be in the next version

**Comment by npurushe** [comment]
The 3.14.0 version has this change

**Comment by vfaSonnt** [comment]
yeah! Thank you very much for your work.
