### ISSUE TITLE
Latest version (13.3.0) gives error when building project with ProGuard enabled

### ISSUE THREAD

**Issue by sebj** [requery/sqlite-android#19]
I updated to the latest version and when building for (beta) release with ProGuard enabled, the following messages prevent me from successfully building:

> Warning: Exception while processing task java.io.IOException: proguard.ParseException: Unexpected keyword 'io.requery.android.database.**' in line 1 of file 'project path../build/intermediates/exploded-aar/io.requery/sqlite-android/3.13.0/proguard.txt'

> Error: Execution failed for task ':app:transformClassesAndResourcesWithProguardForBeta'.
> java.io.IOException: proguard.ParseException: Unexpected keyword 'io.requery.android.database.**' in line 1 of file 'project path../build/intermediates/exploded-aar/io.requery/sqlite-android/3.13.0/proguard.txt'

**Comment by sebj** [comment]
Sorry, all good now – my fault entirely.. Updated to latest version and assumed that was the culprit. Cleaned and rebuilt and all is fine.

**Comment by npurushe** [comment]
Thanks for reporting, please use the 3.13.0-1 version with the fix

**Comment by sebj** [comment]
Thanks! 😃
