### ISSUE TITLE
"JNI FatalError called: RegisterNatives failed.."

### ISSUE THREAD

**Issue by sebj** [requery/sqlite-android#20]
My app accesses an SQLite Database as soon as it's opened, but as of version `3.13.0-1`, it crashes at launch with a [very large stacktrace (linked - `me.sebj.times.beta` is my app's ID)](http://pastebin.com/raw/TgLAg2aS), which includes the message:

>JNI FatalError called: RegisterNatives failed for 'io/requery/android/database/sqlite/SQLiteConnection'; aborting...

My app is being built for release (with ProGuard enabled) and crashes both in an Android Emulator on 5.0, and on my own 5.1.1 device (probably others).

Downgrading to `3.12.2-2` in my Gradle file, building, and running instantly fixes the problem - the app runs perfectly.

**Comment by npurushe** [comment]
This is also related to proguard, will provided an updated rules file that fixes this

**Comment by sebj** [comment]
Ok, thanks

**Comment by npurushe** [comment]
Give these rules a try (in your apps proguard rules), should solve your issue. If so will update them in master
```
-keepclasseswithmembers class io.requery.android.database.** {
  native <methods>;
  public <init>(...);
}
-keepnames class io.requery.android.database.** { *; }
-keep public class io.requery.android.database.sqlite.SQLiteCustomFunction { *; }
-keep public class io.requery.android.database.sqlite.SQLiteCursor { *; }
-keep public class io.requery.android.database.sqlite.SQLiteDebug** { *; }
-keep public class io.requery.android.database.sqlite.SQLiteDatabase { *; }
-keep public class io.requery.android.database.sqlite.SQLiteOpenHelper { *; }
-keep public class io.requery.android.database.sqlite.SQLiteStatement { *; }
-keep public class io.requery.android.database.CursorWindow { *; }
-keepattributes Exceptions,InnerClasses
```

**Comment by sebj** [comment]
I think that's done it! Can't see any issues

**Comment by npurushe** [comment]
ok great!

**Comment by sebj** [comment]
Thanks :)
