### ISSUE TITLE
java.util.concurrent.TimeoutException: SQLiteCursor.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by yuyanghe** [requery/sqlite-android#21]
I use you lib in our project  and receiver crash report like this
java.util.concurrent.TimeoutException: SQLiteCursor.finalize() timed out after 10 seconds

**Comment by npurushe** [comment]
Which version are you using?

**Comment by yuyanghe** [comment]
3.12   are you fix it in the newest version?    what's reaseon?

**Comment by npurushe** [comment]
Having the version can help narrow it down. No changes were really made there, however I would suggest you try to reproduce the problem using the latest version and see if you can collect more information about this issue.

**Comment by npurushe** [comment]
Closing for now since not able to reproduce, if you have more details on this please add them.
