### ISSUE TITLE
JUnit tests: 'no sqlite3x in java.library.path'

### ISSUE THREAD

**Issue by abredykhin** [requery/sqlite-android#22]
When trying to run JUnit tests in Android project I get the following error for any test touching database classes 

`java.lang.UnsatisfiedLinkError: no sqlite3x in java.library.path`

and after first failure I see this error over and over: 

`java.lang.NoClassDefFoundError: Could not initialize class io.requery.android.database.sqlite.SQLiteDatabase`

Is it possible to use this library in tests?

**Comment by abredykhin** [comment]
Closing as duplicate of [#17](https://github.com/requery/sqlite-android/issues/17)

Are you guys going to release updated version?

**Comment by npurushe** [comment]
Yes an updated version will be released in the next couple days

**Comment by MisterRager** [comment]
It looks like that even with the `x86_64` artifacts, the tests still fail. See https://github.com/robolectric/robolectric/issues/1171

**Comment by d2callpod** [comment]
Was this ever resolved?

I'm getting this error `java.lang.UnsatisfiedLinkError: no sqlite3x in java.library.path` when trying to run any unit tests against code using SQLite.

**Comment by MisterRager** [comment]
It cannot be solved simply. Look at robolectric's work to bring in [an ancient version of sqlite](https://mvnrepository.com/artifact/com.almworks.sqlite4java). Apparently, the native libs get dropped from attempts to run unit tests with the android build tools.
