### ISSUE TITLE
json1 issue

### ISSUE THREAD

**Issue by konmik** [requery/sqlite-android#24]
This test does not pass:

    @Test
    public void queryByField() throws Exception {
        SQLiteDatabase db = SQLiteDatabase.create(null);
        db.execSQL("CREATE TABLE test (data TEXT)");
        db.execSQL("INSERT INTO test (data) VALUES (json(?))",
                new String[]{"{\"id\":1,\"name\":\"Joe\"}"});

        Cursor cursor = db.rawQuery(
                "SELECT data FROM test WHERE json_extract(data, '$.id') == ?",
                new String[]{"1"});
        assertEquals(1, cursor.getCount());
    }

What is weird is that it starts working when I replace

                "SELECT data FROM test WHERE json_extract(data, '$.id') == ?",

to

                "SELECT data FROM test WHERE CAST(json_extract(data, '$.id') AS NONE) == ?",

Is it an SQLite issue?

**Comment by npurushe** [comment]
Well ultimately I think you are casting it to a `blob` as `none` is deprecated. If you look at the documentation for json_extract it should be returning an Integer result type so if you bind as a Integer not a String then it looks like it should work. Did you try that?

**Comment by konmik** [comment]
casting it to string and integer - both do work

**Comment by konmik** [comment]
This modification also works:

                "SELECT data FROM test WHERE json_extract(data, '$.id') == CAST(? AS INTEGER)"

It looks like something weird is happening with types inside SQLite

**Comment by npurushe** [comment]
Will be resolved by #25
