### ISSUE TITLE
Add Object[] overload for rawQuery()

### ISSUE THREAD

**Issue by gborland** [requery/sqlite-android#25]
Please consider adding an overload for `SQLiteDatabase.rawQuery` which accepts a plain object array (`Object[]`) as arguments. Currently the argument array can only be strings.

```java
public Cursor rawQuery(String sql, String[] selectionArgs)
```

This contrasts with `execSQL()` which allows a wider range of types to be passed through.

```java
public void execSQL(String sql, Object[] bindArgs)
```

I appreciate there may be reluctance to break away from the official Android SQLiteDatabase API, but this would fix a particularly stupid restriction. This restriction means that since you can't pass a plain integer into a SQL query, your query has to be rewritten to cast the string to an integer instead. Instead of
```SQL
WHERE ?1 = 1
```

we have to write
```SQL
WHERE CAST(?1 as int) = 1
```
instead.

**Comment by konmik** [comment]
It looks like a connected issue to me: https://github.com/requery/sqlite-android/issues/24

**Comment by npurushe** [comment]
I think this proposal should be fine, will try to include it in the next update

**Comment by npurushe** [comment]
The 3.14.0 version has this change
