### ISSUE TITLE
[ENHANCEMENT] Add support for DatabaseUtils class

### ISSUE THREAD

**Issue by malloth** [requery/sqlite-android#28]
I was up to migrate my current project to this SQLite library, but I encountered a small problem. You use custom SQLiteDatabase and SQLiteStatement classes which are incompatible with android.database.DatabaseUtils class.

Can you please add your own implementation of DatabaseUtils, so that migration would be easier for those who use this utility class?

**Comment by npurushe** [comment]
That class is a bit strange. The methods that depend on classes in the sqlite package could have and probably should have just been added to the sqlite classes, probably just bad design. The majority of the methods will still work with this library, will add the incompatible ones on to their corresponding classes.
