### ISSUE TITLE
[ENHANCEMENT] Add SQLiteDatabase.OPEN_SHAREDCACHE flag

### ISSUE THREAD

**Issue by malloth** [requery/sqlite-android#29]
In original Android implementation there's literally no way of opening database with SQLITE_OPEN_SHAREDCACHE flag. Please add this possibility via custom flag for SQLiteDatabase.open(String, SQLiteDatabase.CursorFactory, int) method.

Shared cache is very important when using WAL database transaction between multiple threads with read_uncommitted pragma.

**Comment by npurushe** [comment]
Makes sense, there are a number of other flags missing here that could be added as well
