### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by sakismts** [requery/sqlite-android#36]
Hello 

Can you give an example of adding and getting json records using the io.requery.android.database.sqlite.SQLiteDatabase and io.requery.android.database.sqlite.SQLiteOpenHelper

Thank you
Athan

**Comment by npurushe** [comment]
Hi the behavior is no different than the standard Android database API for which there are plenty of examples on the web. For documentation on the JSON1 extension see https://sqlite.org/json1.html
