### ISSUE TITLE
Is FTS Enhanced Query Syntax enabled?

### ISSUE THREAD

**Issue by mortenholmgaard** [requery/sqlite-android#37]
Is FTS Enhanced Query Syntax enabled in this build? 
ENABLE_FTS3_PARENTHESIS = true?

**Comment by npurushe** [comment]
Hi currently no, but this looks like a simple and safe addition.

**Comment by mortenholmgaard** [comment]
Will you make a release with this?
Perhaps including this: https://github.com/requery/sqlite-android/issues/39

**Comment by npurushe** [comment]
The latest release contains a build with these flags enabled
