### ISSUE TITLE
rankfunc - could it be included?

### ISSUE THREAD

**Issue by mortenholmgaard** [requery/sqlite-android#39]
To be able to rank result with FTS after how good a match the result is, we need to include the rankFunc. 

The rankFunc to include is defined in the bottom of this documentation page:
https://www.sqlite.org/fts3.html

Right now when I try to use the ranking I the this error:

> android.database.sqlite.SQLiteException: no such function: rank (code 1)

I use it like this with a weight for each column:
`ORDER BY rank(matchinfo(tableName), 0.0, 0.0, 1.0, 0.8, 0.0, 0.5, 0.0, 0.1, 0.0, 0.1, 0.1, 0.0, 0.1, 0.0, 0.1, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0) DESC`

**Comment by npurushe** [comment]
That is provided as an example only so not sure it makes sense for it to be included here. While there is a way currently to implement your own function (on the Java API side) it doesn't contain the matching info to be able to that, possibly that can be enhanced in some way or a way to be able to create your function and register at the C/native level.

**Comment by mortenholmgaard** [comment]
We have used this exact code with success in years in iOS production code, so it might just be an example, but it works great to do the exact job of sorting by score. I think most people will look at the sqlite documentation and see that this is the exact method they need, without considering to modify it, because it does support most sorting by score cases. And as you say there is really no other simple way of doing that.
Will you consider adding it? - as I see it there is no real disadvantage of including it. Just add info about it to the readme, so others know it is there so they can use it as well :)

**Comment by mortenholmgaard** [comment]
@npurushe I hope you will take a look at this soon because I am actually waiting to use it 👍

**Comment by MisterRager** [comment]
You can do this yourself. Create a [Run-Time Loadable Extension](https://sqlite.org/loadext.html), and override `SQLiteOpenHelper#createConfiguration` to add them through `SQLiteDatabaseConfiguration#customExtensions` or by using the constructor that injects them. `SQLiteCustomExtension` lets you use any loadable extension you want. If you'd rather define the function in Java, do it with a "custom function", instead.

**Comment by npurushe** [comment]
Closing this one @MisterRager has a good answer on how this can be done.

**Comment by mortenholmgaard** [comment]
I others need a sqlite ranking function:

> ORDER BY rank(matchinfo(tableName), '0.0, 10.0, 3.0, 0.5, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0') DESC

```
    @Override
    protected SQLiteDatabaseConfiguration createConfiguration(String path, int openFlags) {
        SQLiteDatabaseConfiguration configuration = super.createConfiguration(path, openFlags);

        configuration.functions.add(new SQLiteFunction("rank", 2, new SQLiteDatabase.Function() {
            @Override
            public void callback(Args args, Result result) {
                ByteBuffer buffer = ByteBuffer.wrap(args.getBlob(0)).order(ByteOrder.nativeOrder());
                String[] weightsForColumns = args.getString(1).split(", ");
                long numberOfTermsInQuery = buffer.getInt(0);
                long numberOfColumns = buffer.getInt(4);
                double score = 0.0;

                //Documentation: https://www.sqlite.org/fts3.html#matchinfo
                for (int i = 1; i <= numberOfTermsInQuery; i++) {
                    for (int column = 0; column < numberOfColumns; column++) {
                        double hitCount = buffer.getInt((2 + i * column * 3) * 4);
                        double globalHitCount = buffer.getInt((2 + i * column * 3 + 1) * 4);

                        if (hitCount > 0) {
                            double weight = Double.parseDouble(weightsForColumns[column]);
                            double columnScore = (hitCount / globalHitCount) * weight;
                            //Log.d("Ranking", "column " + column + " score: " + columnScore + " (" + hitCount + " / " + globalHitCount + " * " + weight + ")");
                            score += columnScore;
                        }
                    }
                }

                //Log.d("Ranking", "song score: " + score);
                result.set(score);
            }
        }));

        return configuration;
    }
```
