### ISSUE TITLE
[request] interfaces for SQLiteDatabase stuff

### ISSUE THREAD

**Issue by gfx** [requery/sqlite-android#4]
I need an abstraction layer for SQLiteDatabase stuff in order to switch the impl easily.

Do you have a plan about it?

**Comment by npurushe** [comment]
You mean switching to call through `android.database.sqlite.SQLiteDatabase` instead of the embedded version? Could be a possibility incase of something like missing binaries for the cpu architecture

**Comment by gfx** [comment]
I'd like to use sqlite-android in [my ORM](https://github.com/gfx/Android-Orma), but I don't want to force to use sqlite-android to users. It should be optional. I'm not sure how to do so, though.

**Comment by trevjonez** [comment]
You could provide two versions of your AAR one that is the standard version and one that is built with the library dependency then run jarjar links or something to replace the imports. All of which you could capture in a gradle task chain.

**Comment by npurushe** [comment]
Yup that will have to be an interface and implementations you provide. If any such abstraction was provided here it will still require a dependency on this library.

**Comment by gfx** [comment]
:ok:
