### ISSUE TITLE
Android Studio open  sqlite-android (error)

### ISSUE THREAD

**Issue by hui5368** [requery/sqlite-android#40]
Hi, when i was trying to open sqlite-android using android studio, but i have some error about
**SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.**

Does anyone knows how to fix this problem ?

**Comment by Haoxiqiang** [comment]
if environment variable was set,the local.properties will auto create with:
```
sdk.dir=..../sdk
ndk.dir=..../sdk/ndk-bundle
```
please check your env variable
```
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
ANDROID_HOME=~/Library/Android/sdk/
PATH=$PATH:$JAVA_HOME/bin:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/ndk-bundle
```
replace this with your path
