### ISSUE TITLE
Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by thelong1EU** [requery/sqlite-android#42]
Sorry for asking the same question, but it seems you deleted my other issue. Is there a way to stop logging this warning?

```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'close' not called  
```

**Comment by npurushe** [comment]
It's not deleted or even closed https://github.com/requery/sqlite-android/issues/41. Also issues are not deleted only closed. Closing this one as a duplicate
