### ISSUE TITLE
The value of BigDecimal is incorrectly read

### ISSUE THREAD

**Issue by zwieback** [requery/sqlite-android#45]
Hi, I found a bug with reading BigDecimal values.

I have next class:
```java
@Entity(propertyNameStyle = PropertyNameStyle.FLUENT_BEAN)
public interface IOperation extends Observable, Parcelable, Persistable, Serializable {

    @Key
    int getId();

    IOperation setId(int id);

    @Bindable
    @Column(nullable = false, value = "0")
    BigDecimal getValue();
}
```

Then I insert one value like this:
```java
    @Override
    public Observable<Iterable<Operation>> call() {
        Set<Operation> operations = new TreeSet<>(this);
        operations.add(new Operation().setId(1).setValue(new BigDecimal("490000.99")));
        return data.insert(operations).toObservable();
    }
```

Created table in sqlite database:
```sql
CREATE TABLE IOperation (id integer primary key not null, value decimal default 0 not null)
```
with one record with **id** = 1 and **value** = 490000.99

But when value read by method `io.requery.android.database.CursorWindow#getString(int, int)` that use native function `nativeGetString` then method returns value == 490001, not 490000.99

Is it possible to read the recorded value?

**Comment by zwieback** [comment]
The next test failed:
```java
    @Test
    public void testInsertBigDecimal() {
        BigDecimal initialValue = new BigDecimal("490000.99");
        Operation operation = new Operation();
        operation.setId(1);
        operation.setValue(initialValue);
        data.insert(operation);
        assertTrue(operation.getId() > 0);  // on that line operation.getValue() == 490000.99
        Operation cached = data.select(Operation.class)
                .where(Operation.ID.equal(operation.getId()))
                .get().first();
        assertSame(cached, operation);      // on that line operation.getValue() == 490001
        assertEquals(cached.getValue(), initialValue);  // failed on that line
    }
```

**Comment by npurushe** [comment]
Does this issue occur only with requery-sqlite? does it not occur with Android's default sqlite api?

**Comment by zwieback** [comment]
Hi!
I created a table with the `DECIMAL` column type, wrote in this field the value of `new BigDecimal("490000.99").toPlainString()`.

Results:
```
cursor.getString() = 490001
cursor.getFloat() = 490001.0
cursor.getDouble() = 490000.99
```

Results of `new BigDecimal("490000.111333111333")`:
```
cursor.getString() = 490000
cursor.getFloat() = 490001.12
cursor.getDouble() = 490000.11133311136
```

Results of `new BigDecimal("490000.33333333333")`:
```
cursor.getString() = 490000
cursor.getFloat() = 490000.34
cursor.getDouble() = 490000.3333333334
```

Conclusion: not a bug, but a pitfall.

I think to use the advice [from SO](https://stackoverflow.com/a/23023904/8035065)

**Comment by npurushe** [comment]
Hi thanks for confirming that. It may possible to add BigDecimal support as an enhancement in this library at least, will look into that.
