### ISSUE TITLE
custom functions: local reference table overflow

### ISSUE THREAD

**Issue by Fabrik19** [requery/sqlite-android#49]
When using custom functions in the where clause of a query on some devices the app crashes with the following error:

`
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113] JNI ERROR (app bug): local reference table overflow (max=512)
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113] local reference table dump:
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]   Last 10 entries (of 510):
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]       509: 0x707d7400 java.lang.String "1"
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]       508: 0x707d7400 java.lang.String "1"
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]       507: 0x707d7400 java.lang.String "1"
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]       506: 0x707d7400 java.lang.String "1"
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]       505: 0x707d7400 java.lang.String "1"
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]       504: 0x707d7400 java.lang.String "1"
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]       503: 0x707d7400 java.lang.String "1"
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]       502: 0x707d7400 java.lang.String "1"
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]       501: 0x707d7400 java.lang.String "1"
10-25 16:21:02.207 23312-23590/*** A/art: sart/runtime/indirect_reference_table.cc:113]       500: 0x707d7400 java.lang.String "1"
`

The devices on which this crash happens are the Samsung S4 (GT-I9505 Android 5.0.1) and the BQ Aquaris X (Android 7.1.1).

**Comment by Fabrik19** [comment]
Adding the line `env->DeleteLocalRef(result);` in the **sqliteCustomFunctionCallback** function in the **android_database_SQLiteConnection.cpp** around line 246 seems to fix the problem.

**Comment by npurushe** [comment]
Hi thanks for reporting, that sounds like the right fix would you like to submit a PR?
