### ISSUE TITLE
update()/delete() methods on SQLiteDatabase do not accept Object[]

### ISSUE THREAD

**Issue by netvl** [requery/sqlite-android#52]
As opposed to `query()` methods (which, compared to the native Android API, accept `Object[]` for bind arguments), `delete()` and `update()` still require `String[]`. Is this intentional for some reason or just an overlook?

**Comment by gabrielittner** [comment]
Both do exist:
`public int update(String, @ConflictAlgorithm int, ContentValues, String,  Object[])`
https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteDatabase.java#L1681

`public int delete(String, String,  Object[])`
https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteDatabase.java#L1634

**Comment by npurushe** [comment]
Yup these were just added to update/delete in the most recent version, thanks to @gabrielittner
