### ISSUE TITLE
Problem with missing class

### ISSUE THREAD

**Issue by ElmirSecerbegovic** [requery/sqlite-android#69]
After updating to version 3.24.0 we have an issue with missing class android.arch.persistence

"class file for android.arch.persistence.db.SupportSQLiteOpenHelper not found"

**Comment by ElmirSecerbegovic** [comment]
Thank you for the info. This was automatically included with older versions so I probably missed that.

**Comment by mkruczkowski** [comment]
It should be mentioned in `README.md` or it should be included in library

**Comment by danielfaust** [comment]
I just upgraded from `3.23.1` to `3.25.2` and had problems compiling. It took me some time to figure out that I needed to add
```
implementation 'android.arch.persistence:db:1.1.1'
```
to the manifest.
I'm also voting for this info to get added to the README.md

This is a really great project, I hope it never dies. Thank you very much for your effort.

**Comment by gabrielittner** [comment]
Should be fixed by #85

**Comment by gabrielittner** [comment]
Should be fixed by #85

The problem didn't happen in older versions because they were using `compile` which is the equivalent to `api`.
