### ISSUE TITLE
Requery doesn't allow all valid sqlite flags (specifically, NO_LOCALIZED_COLLATORS)

### ISSUE THREAD

**Issue by mikehardy** [requery/sqlite-android#71]
as I work through upgrading AnkiDroid dependencies, I'm stumped taking requery/sqlite-android past 3.16 because commit https://github.com/requery/sqlite-android/commit/6f2070b16a4fbbdcd24c5a4423ded981ef3c5c08 removes NO_LOCALIZED_COLLATORS, which is still present in the sqlite system implementation and is used by our project:

developer.android.com/reference/android/database/sqlite/SQLiteDatabase#NO_LOCALIZED_COLLATORS

I tried simply stripping the flag from the open call in our code, and on existing databases, I get this:

07-03 07:56:59.001 4420-4452/com.ichi2.anki I/CollectionHelper: openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
07-03 07:56:59.024 4420-4452/com.ichi2.anki E/SQLiteLog: (21) misuse at line 142191 of [ada05cfa86]
07-03 07:56:59.025 4420-4452/com.ichi2.anki E/SQLiteDatabase: Failed to open database '/storage/emulated/0/AnkiDroid/collection.anki2'.
android.database.sqlite.SQLiteMisuseException: unknown error (code 21): Could not open database

So it is not valid to remove this flag from the implementation as existing databases created with it must be opened with it

I may be missing a generic way to inject underlying flags into the requery-level open database call but I was unable to find one.

**Comment by mikehardy** [comment]
Hey @npurushe - I don't intend to pester, but is there an update on this? Would a PR be helpful at all? (I don't want to ask for an ETA, I know it's open source, but some projects don't like external PRs either...). Thanks!

**Comment by npurushe** [comment]
Hi If you're passing `NO_LOCALIZED_COLLATORS` to your database instance you are already getting the equivalent behavior in this library because it doesn't include localized collators. This is because it would require a dependency on the ICU library. (ICU support would be added to the ndk in version 19 at which point localized collators would be added but would not be made the default)

How are you getting a SQLiteMisuseException ? Are you trying to pass flags defined in `android.database.sqlite.SQLiteDatabase` into `io.requery.android.database.sqlite.SQLiteDatabase`? that looks like the only case you should get that kind of error, in which case the flags from io.requery.android.database.sqlite.SQLiteDatabase should be used instead. NO_LOCALIZED_COLLATORS is not a real sqlite flag, it's never passed to sqlite in the aosp implementation, instead in aosp valid sqlite flags are extracted from the java flags and then passed to sqlite.

**Comment by npurushe** [comment]
Hi looks like your problem is `SQLiteDatabase.OPEN_READWRITE + SQLiteDatabase.CREATE_IF_NECESSARY` 
flags should not be added instead should be or'd `SQLiteDatabase.OPEN_READWRITE | SQLiteDatabase.CREATE_IF_NECESSARY`

**Comment by mikehardy** [comment]
@npurushe - thank you, with that change I was able to pass our internal tests on 3.16.0 and successfully move our requery dependency from 3.16.0 to 3.23.1. However - and I think this is strange - I was unable to move from 3.23.1 to 3.24.0. I get a compile error here:

```
/home/mike/work/AnkiDroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:190: error: cannot access SupportSQLiteDatabase
            cursor = mDb.getDatabase().rawQuery(
                                      ^
```
Here's a link to that line:
https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L190

It is doing exactly what it seems, getting a handle to a SQLiteDabase object, and calling this rawQuery method:
https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteDatabase.java#L1392


I examined the diff: https://github.com/requery/sqlite-android/compare/3.23.1...3.24.0
... and could see no reason why this code wouldn't even compile?

Similar to the initial problem (incorrect flag usage) I suspect this has nothing to do with requery specifically, but the interaction sure is odd.

**Comment by mikehardy** [comment]
I found the problem, it's the changes related to Gradle scoping, specifically this line is not backwards compatible:
https://github.com/requery/sqlite-android/compare/3.23.1...3.24.0#diff-f4f27db88b7ed3658536e4149d332fc3R47

When I include that library to my dependencies as well, my compile works and my project passes tests.

As an aside, why the 1.0.0 version of that library in place of 1.1.1 (current)? It appears to work in my project:
https://github.com/mikehardy/Anki-Android/commit/e9b4aed32165fc898dbf5e2931a9ac38ac56a3c7

**Comment by mikehardy** [comment]
Hi there! Admittedly pestering but I am curious for the answer on the above comment on library versions / dependencies then I can mark this closed

**Comment by npurushe** [comment]
Hi that diff line link didn't work but if it's about depending on `android.arch.persistence:db` that is a dependency in order to make the library usable in the android arch components

**Comment by mikehardy** [comment]
Ah interesting. Worth noting that with that gradle change, dependent projects now need to add the arch dependency in their gradle files downstream or they'll see build failures (unless my project is unique or misconfigured in some way). I suppose you could have a sub-package to tease that out but it didn't seem a big deal to me, more of a documentation issue. Either way, thanks for the help, we're successfully running on requery current release now
