### ISSUE TITLE
Incorrect SQLiteCursor.getColumnIndex.

### ISSUE THREAD

**Issue by denmiroch** [requery/sqlite-android#77]
getColumnIndex will return same index for any columns with names that have same hashCode.

In this example, AaIndex and BBIndex will be the same
```
CREATE TABLE t ( Aa text, BB text )

Cursor cursor = db.query("t", ...)
int AaIndex = cursor.getColumnIndex("Aa")
int BBIndex = cursor.getColumnIndex("BB")
```

**Comment by denmiroch** [comment]
I cannot reproduce it on android 27. 
Aosp SQLiteCursor uses `Map<String, Integer>.get(name)`, not `Map<Integer, Integer>.get(name.hashCode())` as requery do.

**Comment by npurushe** [comment]
Yes but HashMap<String, Integer> will still end up hashing the string when it's used as a key

**Comment by georgi-neykov-hub** [comment]
It will end up hashing, but on a collision it will also run `equals()` in the `String` key case.
