### ISSUE TITLE
How to use RequerySQLiteOpenHelperFactory with SQLiteDatabaseConfiguration?

### ISSUE THREAD

**Issue by kptlronyttcna** [requery/sqlite-android#82]
I need to load some sqlite extension and use it with room. As far as I know, I have to use SQLiteDatabaseConfiguration to load extensions, but RequerySQLiteOpenHelperFactory does not take any configuration parameters. It does have a constructor taking an Iterable, but i'm not sure how to use that.

**Comment by kptlronyttcna** [comment]
I've got it working by passing a list of `RequerySQLiteOpenHelperFactory.ConfigurationOptions`. But why take an iterable?

**Comment by npurushe** [comment]
`ConfigurationOptions` is an interface that takes an `SQLiteDatabaseConfiguration` as an argument. So you implement `ConfigurationOptions` and do your customization in the implementation. And then pass it into the factory, it can take more than 1 hence the iterable.
