### ISSUE TITLE
e: Supertypes of the following classes cannot be resolved

### ISSUE THREAD

**Issue by freehussain** [requery/sqlite-android#84]
hello, 

i already have io.requery:sqlite-android:3.24.0 and it working fine but after update to io.requery:sqlite-android:3.25.3 an error comes 

e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:

although i have 'android.arch.persistence:db:1.1.1' as dependency included 

kind regards

**Comment by freehussain** [comment]
hello,

thank you for reply , what should i do now? please tell me i can't change to api

can you please fix it from your side or write a solution here

**Comment by mikehardy** [comment]
Did you try including both of the possible dependencies in your gradle build file that were altered in the only commit since the last release?

```
    implementation 'androidx.sqlite:sqlite:2.0.0'	    api 'androidx.sqlite:sqlite:2.0.0'
    implementation 'androidx.core:core:1.0.0'	    api 'androidx.core:core:1.0.0'
```

**Comment by freehussain** [comment]
hello,

a new error comes Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-50:19 to override.

any help?

**Comment by freehussain** [comment]
also i tried to add  tools:replace="android:appComponentFactory" to my application tag in AndroidManifest.xml

any idea?

**Comment by mikehardy** [comment]
I think it is probably a bad idea to include androidx libraries and com.android.support libraries at the same time. I'd go all the way in your app to androidx using the recommended toolchain flags in gradle.properties

```
android.enableJetifier=true
android.useAndroidX=true
```

Once the whole app is on androidx this will likely go away. Easy to try anyway - the AndroidX automated conversion in Android Studio works well

**Comment by freehussain** [comment]
hello,

no sorry still the same issue, any other idea??

**Comment by mikehardy** [comment]
Nope, sorry

**Comment by freehussain** [comment]
hello,

after i do refactor for androidx , every thing is working fine

Android Studio > Refactor Menu > Migrate to AndroidX...


kind regards
