### ISSUE TITLE
sqlite crash when bitmap copy

### ISSUE THREAD

**Issue by hpj831112** [requery/sqlite-android#86]
acktrace:
  #00  pc 000000000001e398  /system/lib64/libc.so (abort+104)
  #01  pc 0000000000007f78  /system/lib64/liblog.so (__android_log_assert+304)
  #02  pc 0000000000144c98  /system/lib64/libandroid_runtime.so (Bitmap_copy(_JNIEnv*, _jobject*, long, int, unsigned char)+704)
  #03  pc 0000000000b3de88  /system/framework/arm64/boot-framework.oat (android.database.CursorWindow.nativeGetBlob [DEDUPED]+168)
  #04  pc 0000000000b8e330  /system/framework/arm64/boot-framework.oat (android.graphics.Bitmap.copy+416)
  #05  pc 0000000000548d88  /system/lib64/libart.so (art_quick_invoke_stub+584)
  #06  pc 00000000000dd2dc  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
  #07  pc 0000000000299dc4  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+340)
  #08  pc 0000000000294428  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+696)
  #09  pc 0000000000533cb4  /system/lib64/libart.so (MterpInvokeVirtualQuick+812)
  #10  pc 000000000053e894  /system/lib64/libart.so (ExecuteMterpImpl+29972)
  #11  pc 0000000000275118  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
  #12  pc 000000000027ad20  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
  #13  pc 0000000000294408  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+664)
  #14  pc 0000000000533cb4  /system/lib64/libart.so (MterpInvokeVirtualQuick+812)
  #15  pc 000000000053e894  /system/lib64/libart.so (ExecuteMterpImpl+29972)
  #16  pc 0000000000275118  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
  #17  pc 0000000000523db8  /system/lib64/libart.so (artQuickToInterpreterBridge+1052)
  #18  pc 0000000000551f0c  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
  #19  pc 00000000005a13a8  /system/framework/arm64/boot-core-oj.oat (java.util.concurrent.FutureTask.run+216)
  #20  pc 00000000005bd6ac  /system/framework/arm64/boot-core-oj.oat (java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run+140)
  #21  pc 00000000005c1624  /system/framework/arm64/boot-core-oj.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+1044)
  #22  pc 00000000005cfc60  /system/framework/arm64/boot-core-oj.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
  #23  pc 00000000001fa7b8  /system/framework/arm64/boot-core-oj.oat (java.lang.Thread.run+72)
  #24  pc 0000000000548d88  /system/lib64/libart.so (art_quick_invoke_stub+584)
  #25  pc 00000000000dd2dc  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
  #26  pc 000000000046cd48  /system/lib64/libart.so (art::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::ArgArray*, art::JValue*, char const*)+104)
  #27  pc 000000000046ded8  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+772)
  #28  pc 0000000000494eb0  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
  #29  pc 0000000000069d78  /system/lib64/libc.so (__pthread_start(void*)+36)
  #30  pc 000000000001fb80  /system/lib64/libc.so (__start_thread+68)

**Comment by npurushe** [comment]
I don't see this library in the stacktrace. If you are copying the bitmap out of the db, make sure it wasn't truncated and you are using a consistent bitmap format.
