### ISSUE TITLE
Support for SQLDroid ?

### ISSUE THREAD

**Issue by Rockvole** [requery/sqlite-android#87]
Hi,
I was wondering whether you believe your library would work with SQLDroid ?
https://github.com/SQLDroid/SQLDroid

I have been trying to convert SQLDroid to work with your library in my App by renaming the android.database.sqlite libraries, but I am getting an error :

L75 from this file [SQLiteDatabase.java](https://github.com/SQLDroid/SQLDroid/blob/master/src/main/java/org/sqldroid/SQLiteDatabase.java)

        sqliteDatabase = io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(dbQname, null, flags );

<i>error: cannot access SupportSQLiteDatabase
class file for androidx.sqlite.db.SupportSQLiteDatabase not found</i>

**Comment by npurushe** [comment]
You may need to add a dependency to the androidx library if you dont have them in your project

```
dependencies {
    api 'androidx.sqlite:sqlite:2.0.0'
    api 'androidx.core:core:1.0.1'
}
```
